### ISSUE TITLE
Chore: K8s API deprecation

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas-charts#4]
The current canvas charts use K8s API version that are being deprecated. Helm install on K8s 1.20 gives the following warnings:

```W0215 16:15:36.525911    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:36.551914    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:36.610086    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:36.654040    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:38.673837    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:38.686349    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:38.692402    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:38.697468    8143 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0215 16:15:39.838352    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0215 16:15:39.845444    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0215 16:15:39.853979    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
W0215 16:15:39.860710    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
W0215 16:15:40.106198    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0215 16:15:40.120092    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0215 16:15:40.134541    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
W0215 16:15:40.147665    8143 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
```

**Comment by tomkivlin** [comment]
I don't get the `apiextensions.k8s.io/v1beta1` errors, only the `rbac.authorization.k8s.io/v1beta1` - updated in #21.

**Comment by tomkivlin** [comment]
@brian-burton I thought #21 was going to be merged in the last sprint - was there a reason it wasn't?

@pmjordan I did the work some time ago, but could you try the artefacts in the PR branch and see if it works for you?  https://github.com/tomkivlin/oda-canvas-charts/tree/patch-1

**Comment by pmjordan** [comment]
Thank you for your reply @tomkivlin . Frustratingly I have never been able to fully install canvas. I tried your patch-1 on microk8s 1.21.
I got this error:
`*********************************************************************
Installing base canvas
*********************************************************************

W1102 15:03:08.754089 2920459 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
W1102 15:03:10.307269 2920459 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
W1102 15:03:10.315164 2920459 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
NAME: canvas
LAST DEPLOYED: Tue Nov  2 15:03:06 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

*********************************************************************
Installing Keycloak
*********************************************************************

Error: create: failed to create: namespaces "canvas" not found

*********************************************************************
Installing Kafka
*********************************************************************

WARNING: This chart is deprecated
W1102 15:04:13.748227 2924906 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: create: failed to create: namespaces "canvas" not found
`

and then after manually adding namespace canvas I got
`*********************************************************************
Installing base canvas
*********************************************************************

Error: cannot re-use a name that is still in use

Canvas base install failed`

**Comment by tomkivlin** [comment]
Hmm, I will take a look - ta.
