### ISSUE TITLE
upgrade dependency version of postgresql in canvas/charts/keycloak/Chart.yaml

### ISSUE THREAD

**Issue by 9n** [tmforum-oda/oda-canvas-charts#48]
## Description

Current postgresql dependency version in `canvas/charts/keycloak/Chart.yaml` is `10.x.x`, which can't be found in repository.

pls upgrade the version and related parameters in `values.yaml`

**Comment by LesterThomas** [comment]
This has been resolved in https://github.com/tmforum-oda/oda-canvas-charts/blob/master/installation/canvas-oda/Chart.yaml
